def foo
  return if need_return?

  bar
end

def baz
  raise "error" unless valid?

  do_work
end

def quux
  return unless something?

  process
end

def notice_params
  return @notice_params if @notice_params

  @notice_params = params[:data] || request.raw_post
  if @notice_params.blank?
    fail ParamsError, "Need a data params in GET or raw post data"
  end

  @notice_params
end

# Guard clause followed by bare raise (not a guard line)
def exception_class
  return @exception_class if @exception_class

  raise NotImplementedError, "error response must define #exception_class"
end

# Guard clause with `and return` form
def with_and_return
  render :foo and return if condition

  do_something
end

# Guard clause with `or return` form
def with_or_return
  render :foo or return if condition

  do_something
end

# Guard clause before `begin` keyword
def guard_before_begin
  return another_object if something_different?

  begin
    bar
  rescue SomeException
    baz
  end
end

# Guard clause followed by rubocop:disable comment (no blank line between)
def guard_then_rubocop_disable
  return if condition

  # rubocop:disable Department/Cop
  bar
  # rubocop:enable Department/Cop
end

# Guard clause followed by rubocop:enable comment then code (no blank after enable)
def guard_then_rubocop_enable
  # rubocop:disable Department/Cop
  return if condition
  # rubocop:enable Department/Cop

  bar
end

# Guard followed by rubocop:disable directive (not an allowed directive)
def guard_with_disable_directive
  return if need_return?

  # rubocop:disable Metrics/AbcSize

  bar
  # rubocop:enable Metrics/AbcSize
end

# Guard clause followed by regular comment then blank line then code (FP fix)
# RuboCop checks the immediate next line, not the first code line
def guard_comment_then_blank
  return if condition

  # This is a regular comment

  bar
end

# Guard clause with heredoc argument (FN fix)
def guard_with_heredoc
  raise ArgumentError, <<-MSG unless path
    Must be called with mount point
  MSG

  bar
end

# Guard clause with squiggly heredoc
def guard_with_squiggly_heredoc
  raise ArgumentError, <<~MSG unless path
    Must be called with mount point
  MSG

  bar
end

# Ternary guard clause
def ternary_guard
  puts 'some action happens here'
rescue => e
  a_check ? raise(e) : other_thing

  true
end

# FN fix: guard clause followed by if block with multi-line raise
def guard_then_if_multiline_raise
  return if !argv

  if argv.empty? || argv.length > 2
    raise Errors::CLIInvalidUsage,
      help: opts.help.chomp
  end
end

# FN fix: guard followed by if-block with modifier-form return (NOT a guard per RuboCop)
def guard_then_if_modifier_return
  return unless doc.blocks?

  if (first_block = doc.blocks[0]).context == :preamble
    return unless (first_block = first_block.blocks[0])
  elsif first_block.context == :section
    return
  end
end

# FN fix: block-form guard `unless..raise..end` followed by non-guard code
def block_guard_then_nonguard
  unless valid?(level)
    raise "invalid"
  end

  if logger.respond_to?(:add)
    logger.add(level, message)
  else
    raise "invalid logger"
  end
end

# FN fix: simple guard clause patterns missing empty line
def ask_user(question)
  return true if args['-y']

  $stderr.print question
  $stdin.gets =~ /\Aye?s?\Z/i
end

def format_time(time)
  return '' unless time.respond_to?(:strftime)

  time.strftime('%H:%M:%S')
end

def parse_entry(entry)
  next unless entry.end

  entry.update :sheet => "_value"
end

# FN fix: guard followed by bare return (not a guard line) where the return
# line happens to contain `?` in a method name — should NOT be suppressed
# by ternary guard check
def generated_thrift?
  return false unless THRIFT_EXTENSIONS.include?(extname)

  return lines.first(6).any? { |l| l.include?("Autogenerated") }
end

# FN fix: multiple consecutive `return false unless` followed by bare return
def vcr_cassette?
  return false unless extname == '.yml'
  return false unless lines.count > 2

  return lines[-2].include?("recorded_with: VCR")
end

# FN fix: guard followed by bare return with no `?` but still not a guard line
def check_overflow(av, bv)
  reset_state()
  return  unless av.kind_of?(Integer) && bv.kind_of?(Integer)

  @expected = compute(av, bv)
end

# FN fix: return nil if followed by code (bare return with `if`)
def test_login
  s = Etc.getlogin
  return if s == nil

  assert(s.is_a?(String), "must return a String or nil")
end

# FN fix: bare return with ternary value is not a ternary guard sibling
def namespace
  return 'Object' if duck_type?

  return (name == 'Class' || name == 'Module') && !subtypes.empty? ? subtypes.first.name : name
end

# FN fix: next line contains an embedded guard inside a block, not a guard sibling
def update?(cookies)
  return true if cached.empty?

  cookies.each { |key, value| return true if previous_cookie(key) != value }
  false
end

# FN fix: next sibling if-block is not a guard when `and return` is nested in braces
def find_executable(bin, exts)
  return bin if executable_file.call(bin)

  if exts
    exts.each { |ext| executable_file.call(file = bin + ext) and return file }
  end
  nil
end

# FN fix: multi-branch if/elsif guard block followed by code
def display_name(first_name, last_name, login)
  if first_name.blank? && last_name.blank?
    return login
  elsif first_name.blank?
    return last_name
  elsif last_name.blank?
    return first_name
  end

  "#{first_name} #{last_name}"
end

# FN fix: guard followed by `::Kernel.raise` (qualified receiver) — NOT a guard clause
# The next line should NOT suppress the offense because `::Kernel.raise` has
# a receiver, so it doesn't match RuboCop's (send nil? {:raise :fail} ...).
def dirname(path, level = 1)
  return path if level == 0

  ::Kernel.raise ::ArgumentError, "level can't be negative" if level < 0
end

# FN fix: guard followed by line with `next!` method call — NOT a guard keyword
# `next!` is a method name, not the `next` keyword.
def advance_draft_sequence
  return if topic.blank?

  DraftSequence.next!(last_editor_id, topic.draft_key) if last_editor_id
end

# FN fix: guard followed by line with `fail!` method call — NOT a guard keyword
def check_thread_exists(params, channel)
  return if params.thread_id.blank?

  fail!("Thread not found") if !channel.threads.exists?(id: params.thread_id)
end

# FN fix: guard with UTF-8 characters (multi-byte) followed by code
def result_emoji
  return "✅" if success?

  ""
end

# FN fix: guard with UTF-8 in condition followed by code
def ignore_searx
  return unless params[:utf8] == "✓"

  @search = Search.new({results_count: 0}, nil)
end

# FN fix: block-form if/else/end where if-branch is a raise guard
def add_disk(size)
  if @disk_change == :deleted
    raise RuntimeError, "Can't add a disk w/o saving changes or reloading"
  else
    load_unless_loaded!
  end

  true
end

# FN fix: block-form if/else/end with `or raise` in if-branch as guard
def delete_disk(number)
  if @disk_change == :added
    raise RuntimeError, "Can't delete a disk w/o saving changes or reloading"
  else
    load_unless_loaded!
    @disk_change = :deleted
  end

  true
end

# FN fix: block-form if/else/end with multi-line `or raise` — RuboCop checks
# the RHS of the `or` node for single_line?, not the whole expression
def accept(t, pat, &block)
  if pat
    pat.respond_to?(:match) ||
      raise(TypeError, "has no `match'")
  else
    pat = t if t.respond_to?(:match)
  end

  unless block
    block = pat.method(:convert).to_proc
  end
end

# FN fix: guard followed by multi-line raise with `+` continuation in next
# sibling — multi-line raise is NOT single_line?, so not a valid guard for suppression
def times(number)
  raise "times(N) accepts integers >= 1 only" if !number.is_a?(Integer)

  if @responses_sequences.empty?
    raise "Invalid WebMock stub declaration." +
      " times(N) can be declared only after response declaration."
  end
end

# FN fix: unless/else with guard in unless body (the unless body is the
# if_branch in RuboCop's AST, so raise is the guard clause)
def unless_else_guard
  unless cond
    raise "error"
  else
    do_thing
  end

  next_code
end

# FN fix: multiline guard (block in condition) with semicolon-separated
# next statement on the guard's end line
def multiline_guard_semicolon
  raise "bad" if !u = items.find { |x|
    x.valid?
  }; do_something

end

# FN fix: block-form guard followed by `if..raise..end` whose raise string spans
# multiple lines, so the next if-block is not a guard clause.
def block_guard_then_if_multiline_string_raise(connect_string)
  if GitRepository.repository_exists?(connect_string)
    raise RepositoryCollision, "There is already a repository at #{connect_string}"
  end

  if File.exist?(connect_string)
    raise IOError, "Could not create a repository at #{connect_string}: some directory with same name exists
                         already"
  end
end

# FN fix: next sibling uses rescue modifier, so it is not itself a guard clause.
def rating_average
  return self.rating_avg if attributes.has_key?('rating_avg')

  return (rating_statistic.rating_avg || 0) rescue 0 if acts_as_rated_options[:stats_class]
  avg
end

# FN fix: rescue modifier around the next line should not suppress the offense.
def determine_lease_type
  return nil if group.nil?

  return "ip" if IPAddr.new(group) rescue false
  return "local" if Admin::Group.exists? group

  return "external"
end

# FN fix: ternary guard detection must ignore ternaries nested inside an if
# condition block literal.
def guard_then_if_with_ternary_break_in_condition(remaining)
  return if remaining.empty?

  if remaining.find { |n| (type = n.type) == :blank ? nil : ((BLOCK_TYPES.include? type) ? true : break) }
    el.options[:compound] = true
  end
end

# FN fix: comment text containing `if` must not make a bare return look like a guard.
def output_extension(mime)
  return '.css' if mime.eql? 'text/css'

  return '.html' # if all else falls trough
end

# FN fix: next sibling with nested `if ... unless ...` is not itself a guard clause
def guard_then_nested_modifier_not_guard(path, replace, name, opts)
  return unless name && opts

  return if File.exist?(path) unless replace
  work
end

# FN fix: next sibling with a statement before `return if` is not a guard clause
def guard_then_semicolon_modifier_guard
  verify_file_download_permissions(@study); return if performed?

  execute_file_download(@study); return if performed?
end

# FN fix: `if ... == :return` is not a guard just because the symbol is named `:return`
def guard_then_if_with_symbol_literal(node, result)
  next if SKIPPABLE.include?(node.type)

  if node.type == :return
    result.concat reduce_to_value_nodes([node.children[0]])
    # Return the result here because the rest of the code is
    # unreachable
    return result
  else
    result.concat explicit_return_values_from_compound_statement(node)
  end
end

# FN fix: first body line of the next `if` block can be a multiline ternary return
def guard_then_if_with_multiline_ternary_return(expr)
  return (@options[:html] ? %(<a href="#grammar-production-#{@coder.encode expr}">#{@coder.encode expr}</a>) : expr.to_s) if expr.is_a?(Symbol)

  if expr.is_a?(String)
    return expr.length == 1 ?
      format_ebnf_char(expr) :
      format_ebnf_string(expr)
  end
end

# FN fix: consecutive semicolon-prefixed guards still need empty lines between them
def guard_chain_with_semicolon_prefix(message)
  fnid = message['from']; return [] unless fnid

  fnode = @execution['nodes'][fnid]; return [] unless fnode

  remove_node(message, fnode) +
    leave_tags(message, fnode)
end

# FN fix: multiple semicolon-prefixed guards in sequence
def parent_is_trap?
  pt = parent_node_tree; return false unless pt

  pt0 = pt[0]; return false unless pt0.is_a?(String)

  pro = Flor::Procedure[pt0]; return false unless pro

  pro.names.include?('trap')
end

# FN fix: nested same-keyword modifiers are not guard siblings, so the previous
# guard line still needs a blank line
def nested_same_keyword_guard
  return false if nil?

  return false if empty? if respond_to?(:empty?)
  true
end

# FN fix: guard clause with trailing semicolon
def guard_with_trailing_semicolon
  return unless driver =~ /mysql/i;

  migrate! if tests.include?(:create)
end

# FN fix: guard clause with trailing semicolon then comment
def guard_with_semicolon_and_comment
  return "" if ex_obj == nil; # canceled

  ex_obj.cb_call
end

# FN fix: break guard with trailing semicolon in a block
def guard_break_with_semicolon
  loop do
    break if file.eof?;

    readed << file.read(100)
  end
end

# FN fix: guard followed by multi-line next sibling with `return...do...end`
# RuboCop's `single_line?` returns false for `return x.map do |c| ... end`
def guard_then_if_with_return_do_block
  unless attributes_class.is_a?(Class)
    raise "Unable to set default_attributes"
  end

  if attributes_class.table_exists?
    return attributes_class.columns.map do |c|
      OpenStruct.new({ name: c.name.to_sym })
    end
  end
end

# FN fix: guard followed by next guard with `\` between raise args
# The next guard's raise args span multiple lines, so it's NOT single_line?
def guard_then_multiline_raise_args_continuation
  raise ArgumentError, "Parameters must be provided in a Hash." unless opts.is_a?(Hash)

  raise ArgumentError, "The name parameter is not allowed, use id instead in format:"\
    "1e0b427a-aaaa-bbbb-1111-ee558463ebbf" if opts.key?(:name)

  work
end

# FN fix: guard followed by if block with operator guard + modifier (NOT a guard)
# RuboCop's `guard_clause?` checks `if_branch.guard_clause?`. The if-branch
# is `unless cond; do_thing and return; end`. The `unless` wrapper with
# `and return` inside is a guard clause — but RuboCop doesn't suppress
# the offense when the next sibling is a non-guard block-form `if` whose
# body is a modifier-form guard.
def guard_then_if_with_operator_guard_modifier
  errors.add(:base, "Not found") and return if c.nil?

  if c.closed?
    errors.add(:base, "Not open") and return unless c.user_is_maintainer?(current_user)
  end
  add_to_collection(c)
end

# FN fix: guard with heredoc in CONDITION (not body)
# RuboCop's `last_heredoc_argument` only finds heredocs in the guard's
# body/arguments, not in the `if` condition. The blank line should be
# right after the `return if ...` line, not after the heredoc end marker.
def guard_with_heredoc_in_condition
  return if previous_version_prompt && !yes?(<<~MSG, :red)
    The default preferences update process is only supported.
    Are you sure you want to continue? (y/N)
  MSG

  from = options[:from]
end

# FN fix: break guard in nested block without semicolon
def guard_break_in_nested_if
  if count >= 2
    break unless byte = scanner.get_byte

    # comment
    if byte == ?>
      break
    end
  end
end

# Guard followed by multiline guard with `\` between args — not single_line? so not suppressed
def consecutive_guards_backslash_between_args
  raise ArgumentError, "param1 required" unless opts.is_a?(Hash)

  raise ArgumentError, "The name is"\
    " not allowed" if opts.key?(:name)
end
