def foo
  return if need_return?

  bar
end

def baz
  raise "error" unless valid?

  do_work
end

def quux
  return unless something?

  process
end

def notice_params
  return @notice_params if @notice_params

  @notice_params = params[:data] || request.raw_post
  if @notice_params.blank?
    fail ParamsError, "Need a data params in GET or raw post data"
  end

  @notice_params
end

# Guard clause followed by bare raise (not a guard line)
def exception_class
  return @exception_class if @exception_class

  raise NotImplementedError, "error response must define #exception_class"
end

# Guard clause with `and return` form
def with_and_return
  render :foo and return if condition

  do_something
end

# Guard clause with `or return` form
def with_or_return
  render :foo or return if condition

  do_something
end

# Guard clause before `begin` keyword
def guard_before_begin
  return another_object if something_different?

  begin
    bar
  rescue SomeException
    baz
  end
end

# Guard clause followed by rubocop:disable comment (no blank line between)
def guard_then_rubocop_disable
  return if condition

  # rubocop:disable Department/Cop
  bar
  # rubocop:enable Department/Cop
end

# Guard clause followed by rubocop:enable comment then code (no blank after enable)
def guard_then_rubocop_enable
  # rubocop:disable Department/Cop
  return if condition
  # rubocop:enable Department/Cop

  bar
end

# Guard followed by rubocop:disable directive (not an allowed directive)
def guard_with_disable_directive
  return if need_return?

  # rubocop:disable Metrics/AbcSize

  bar
  # rubocop:enable Metrics/AbcSize
end

# Guard clause followed by regular comment then blank line then code (FP fix)
# RuboCop checks the immediate next line, not the first code line
def guard_comment_then_blank
  return if condition

  # This is a regular comment

  bar
end

# Guard clause with heredoc argument (FN fix)
def guard_with_heredoc
  raise ArgumentError, <<-MSG unless path
    Must be called with mount point
  MSG

  bar
end

# Guard clause with squiggly heredoc
def guard_with_squiggly_heredoc
  raise ArgumentError, <<~MSG unless path
    Must be called with mount point
  MSG

  bar
end

# Ternary guard clause
def ternary_guard
  puts 'some action happens here'
rescue => e
  a_check ? raise(e) : other_thing

  true
end

# FN fix: guard clause followed by if block with multi-line raise
def guard_then_if_multiline_raise
  return if !argv

  if argv.empty? || argv.length > 2
    raise Errors::CLIInvalidUsage,
      help: opts.help.chomp
  end
end

# FN fix: guard followed by if-block with modifier-form return (NOT a guard per RuboCop)
def guard_then_if_modifier_return
  return unless doc.blocks?

  if (first_block = doc.blocks[0]).context == :preamble
    return unless (first_block = first_block.blocks[0])
  elsif first_block.context == :section
    return
  end
end

# FN fix: block-form guard `unless..raise..end` followed by non-guard code
def block_guard_then_nonguard
  unless valid?(level)
    raise "invalid"
  end

  if logger.respond_to?(:add)
    logger.add(level, message)
  else
    raise "invalid logger"
  end
end

# FN fix: simple guard clause patterns missing empty line
def ask_user(question)
  return true if args['-y']

  $stderr.print question
  $stdin.gets =~ /\Aye?s?\Z/i
end

def format_time(time)
  return '' unless time.respond_to?(:strftime)

  time.strftime('%H:%M:%S')
end

def parse_entry(entry)
  next unless entry.end

  entry.update :sheet => "_value"
end

# FN fix: guard followed by bare return (not a guard line) where the return
# line happens to contain `?` in a method name — should NOT be suppressed
# by ternary guard check
def generated_thrift?
  return false unless THRIFT_EXTENSIONS.include?(extname)

  return lines.first(6).any? { |l| l.include?("Autogenerated") }
end

# FN fix: multiple consecutive `return false unless` followed by bare return
def vcr_cassette?
  return false unless extname == '.yml'
  return false unless lines.count > 2

  return lines[-2].include?("recorded_with: VCR")
end

# FN fix: guard followed by bare return with no `?` but still not a guard line
def check_overflow(av, bv)
  reset_state()
  return  unless av.kind_of?(Integer) && bv.kind_of?(Integer)

  @expected = compute(av, bv)
end

# FN fix: return nil if followed by code (bare return with `if`)
def test_login
  s = Etc.getlogin
  return if s == nil

  assert(s.is_a?(String), "must return a String or nil")
end

# FN fix: bare return with ternary value is not a ternary guard sibling
def namespace
  return 'Object' if duck_type?

  return (name == 'Class' || name == 'Module') && !subtypes.empty? ? subtypes.first.name : name
end

# FN fix: next line contains an embedded guard inside a block, not a guard sibling
def update?(cookies)
  return true if cached.empty?

  cookies.each { |key, value| return true if previous_cookie(key) != value }
  false
end

# FN fix: next sibling if-block is not a guard when `and return` is nested in braces
def find_executable(bin, exts)
  return bin if executable_file.call(bin)

  if exts
    exts.each { |ext| executable_file.call(file = bin + ext) and return file }
  end
  nil
end

# FN fix: multi-branch if/elsif guard block followed by code
def display_name(first_name, last_name, login)
  if first_name.blank? && last_name.blank?
    return login
  elsif first_name.blank?
    return last_name
  elsif last_name.blank?
    return first_name
  end

  "#{first_name} #{last_name}"
end

# FN fix: guard followed by `::Kernel.raise` (qualified receiver) — NOT a guard clause
# The next line should NOT suppress the offense because `::Kernel.raise` has
# a receiver, so it doesn't match RuboCop's (send nil? {:raise :fail} ...).
def dirname(path, level = 1)
  return path if level == 0

  ::Kernel.raise ::ArgumentError, "level can't be negative" if level < 0
end

# FN fix: guard followed by line with `next!` method call — NOT a guard keyword
# `next!` is a method name, not the `next` keyword.
def advance_draft_sequence
  return if topic.blank?

  DraftSequence.next!(last_editor_id, topic.draft_key) if last_editor_id
end

# FN fix: guard followed by line with `fail!` method call — NOT a guard keyword
def check_thread_exists(params, channel)
  return if params.thread_id.blank?

  fail!("Thread not found") if !channel.threads.exists?(id: params.thread_id)
end

# FN fix: guard with UTF-8 characters (multi-byte) followed by code
def result_emoji
  return "✅" if success?

  ""
end

# FN fix: guard with UTF-8 in condition followed by code
def ignore_searx
  return unless params[:utf8] == "✓"

  @search = Search.new({results_count: 0}, nil)
end

# FN fix: block-form if/else/end where if-branch is a raise guard
def add_disk(size)
  if @disk_change == :deleted
    raise RuntimeError, "Can't add a disk w/o saving changes or reloading"
  else
    load_unless_loaded!
  end

  true
end

# FN fix: block-form if/else/end with `or raise` in if-branch as guard
def delete_disk(number)
  if @disk_change == :added
    raise RuntimeError, "Can't delete a disk w/o saving changes or reloading"
  else
    load_unless_loaded!
    @disk_change = :deleted
  end

  true
end
