#!/usr/bin/env python3
from __future__ import annotations
"""Dispatch a cop-fix task to Kilo Cloud Agent.

Sends a pre-generated task packet to Kilo via their webhook/API.
The task packet contains everything the agent needs to fix one cop.

Usage:
    python3 scripts/agent/kilo_dispatch.py --task /tmp/task.md --cop Style/NegatedWhile
    python3 scripts/agent/kilo_dispatch.py --task /tmp/task.md --cop Style/NegatedWhile --dry-run

Environment:
    KILO_API_KEY      - Kilo API key (or set in --api-key)
    KILO_WEBHOOK_URL  - Kilo webhook trigger URL (or set in --webhook-url)
"""

import argparse
import json
import os
import sys
import urllib.request
import urllib.error
from pathlib import Path


def dispatch_to_kilo(
    task_content: str,
    cop: str,
    webhook_url: str,
    api_key: str,
    branch: str = "",
    dry_run: bool = False,
) -> dict:
    """Send a task to Kilo Cloud Agent via webhook."""

    if dry_run:
        print(f"DRY RUN: Would dispatch to {webhook_url}")
        print(f"  Cop: {cop}")
        print(f"  Branch: {branch}")
        print(f"  Task size: {len(task_content):,} chars")
        return {"status": "dry_run"}

    # Send task prompt as plain text body. The Kilo webhook template
    # uses {{body}} to inject this directly as the agent's prompt.
    data = task_content.encode("utf-8")
    headers = {
        "Content-Type": "text/plain",
    }
    # Kilo webhook inbound auth — include shared secret if configured.
    # Kilo may expect Authorization header or a custom header name.
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    req = urllib.request.Request(webhook_url, data=data, headers=headers, method="POST")

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = resp.read().decode("utf-8")
            print(f"Dispatched {cop} to Kilo: {resp.status}")
            if body.strip():
                print(f"  Response: {body.strip()}")
            return {"status": "dispatched", "http_status": resp.status}
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        print(f"Error dispatching {cop}: HTTP {e.code}", file=sys.stderr)
        print(f"  Response: {body}", file=sys.stderr)
        sys.exit(1)
    except urllib.error.URLError as e:
        print(f"Error dispatching {cop}: {e.reason}", file=sys.stderr)
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Dispatch a cop-fix task to Kilo Cloud Agent")
    parser.add_argument("--task", type=Path, required=True,
                        help="Path to task.md (generated by generate-cop-task.py)")
    parser.add_argument("--cop", required=True,
                        help="Cop name (e.g., Style/NegatedWhile)")
    parser.add_argument("--branch", default="",
                        help="Pre-created branch name for this job")
    parser.add_argument("--webhook-url", default=None,
                        help="Kilo webhook URL (default: KILO_WEBHOOK_URL env)")
    parser.add_argument("--api-key", default=None,
                        help="Kilo API key (default: KILO_API_KEY env)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be sent without dispatching")
    args = parser.parse_args()

    webhook_url = args.webhook_url or os.environ.get("KILO_WEBHOOK_URL")
    api_key = args.api_key or os.environ.get("KILO_API_KEY")

    if not args.dry_run:
        if not webhook_url:
            print("Error: KILO_WEBHOOK_URL not set. Use --webhook-url or set env var.",
                  file=sys.stderr)
            sys.exit(1)
        if not api_key:
            print("Error: KILO_API_KEY not set. Use --api-key or set env var.",
                  file=sys.stderr)
            sys.exit(1)

    task_content = args.task.read_text()
    if not task_content.strip():
        print("Error: task file is empty", file=sys.stderr)
        sys.exit(1)

    dispatch_to_kilo(
        task_content=task_content,
        cop=args.cop,
        webhook_url=webhook_url or "",
        api_key=api_key or "",
        branch=args.branch,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    main()
