#![allow(dead_code)]
//! Node type constants and dispatch helpers for the batched walker.
//!
//! Generated from ruby_prism::Node enum (151 variants).
//! Maps each Prism AST node type to a u8 tag for O(1) dispatch table lookup.

/// Total number of distinct node types in Prism.
pub const NODE_TYPE_COUNT: usize = 151;

// Node type tag constants.
pub const ALIAS_GLOBAL_VARIABLE_NODE: u8 = 0;
pub const ALIAS_METHOD_NODE: u8 = 1;
pub const ALTERNATION_PATTERN_NODE: u8 = 2;
pub const AND_NODE: u8 = 3;
pub const ARGUMENTS_NODE: u8 = 4;
pub const ARRAY_NODE: u8 = 5;
pub const ARRAY_PATTERN_NODE: u8 = 6;
pub const ASSOC_NODE: u8 = 7;
pub const ASSOC_SPLAT_NODE: u8 = 8;
pub const BACK_REFERENCE_READ_NODE: u8 = 9;
pub const BEGIN_NODE: u8 = 10;
pub const BLOCK_ARGUMENT_NODE: u8 = 11;
pub const BLOCK_LOCAL_VARIABLE_NODE: u8 = 12;
pub const BLOCK_NODE: u8 = 13;
pub const BLOCK_PARAMETER_NODE: u8 = 14;
pub const BLOCK_PARAMETERS_NODE: u8 = 15;
pub const BREAK_NODE: u8 = 16;
pub const CALL_AND_WRITE_NODE: u8 = 17;
pub const CALL_NODE: u8 = 18;
pub const CALL_OPERATOR_WRITE_NODE: u8 = 19;
pub const CALL_OR_WRITE_NODE: u8 = 20;
pub const CALL_TARGET_NODE: u8 = 21;
pub const CAPTURE_PATTERN_NODE: u8 = 22;
pub const CASE_MATCH_NODE: u8 = 23;
pub const CASE_NODE: u8 = 24;
pub const CLASS_NODE: u8 = 25;
pub const CLASS_VARIABLE_AND_WRITE_NODE: u8 = 26;
pub const CLASS_VARIABLE_OPERATOR_WRITE_NODE: u8 = 27;
pub const CLASS_VARIABLE_OR_WRITE_NODE: u8 = 28;
pub const CLASS_VARIABLE_READ_NODE: u8 = 29;
pub const CLASS_VARIABLE_TARGET_NODE: u8 = 30;
pub const CLASS_VARIABLE_WRITE_NODE: u8 = 31;
pub const CONSTANT_AND_WRITE_NODE: u8 = 32;
pub const CONSTANT_OPERATOR_WRITE_NODE: u8 = 33;
pub const CONSTANT_OR_WRITE_NODE: u8 = 34;
pub const CONSTANT_PATH_AND_WRITE_NODE: u8 = 35;
pub const CONSTANT_PATH_NODE: u8 = 36;
pub const CONSTANT_PATH_OPERATOR_WRITE_NODE: u8 = 37;
pub const CONSTANT_PATH_OR_WRITE_NODE: u8 = 38;
pub const CONSTANT_PATH_TARGET_NODE: u8 = 39;
pub const CONSTANT_PATH_WRITE_NODE: u8 = 40;
pub const CONSTANT_READ_NODE: u8 = 41;
pub const CONSTANT_TARGET_NODE: u8 = 42;
pub const CONSTANT_WRITE_NODE: u8 = 43;
pub const DEFINED_NODE: u8 = 44;
pub const DEF_NODE: u8 = 45;
pub const ELSE_NODE: u8 = 46;
pub const EMBEDDED_STATEMENTS_NODE: u8 = 47;
pub const EMBEDDED_VARIABLE_NODE: u8 = 48;
pub const ENSURE_NODE: u8 = 49;
pub const FALSE_NODE: u8 = 50;
pub const FIND_PATTERN_NODE: u8 = 51;
pub const FLIP_FLOP_NODE: u8 = 52;
pub const FLOAT_NODE: u8 = 53;
pub const FOR_NODE: u8 = 54;
pub const FORWARDING_ARGUMENTS_NODE: u8 = 55;
pub const FORWARDING_PARAMETER_NODE: u8 = 56;
pub const FORWARDING_SUPER_NODE: u8 = 57;
pub const GLOBAL_VARIABLE_AND_WRITE_NODE: u8 = 58;
pub const GLOBAL_VARIABLE_OPERATOR_WRITE_NODE: u8 = 59;
pub const GLOBAL_VARIABLE_OR_WRITE_NODE: u8 = 60;
pub const GLOBAL_VARIABLE_READ_NODE: u8 = 61;
pub const GLOBAL_VARIABLE_TARGET_NODE: u8 = 62;
pub const GLOBAL_VARIABLE_WRITE_NODE: u8 = 63;
pub const HASH_NODE: u8 = 64;
pub const HASH_PATTERN_NODE: u8 = 65;
pub const IF_NODE: u8 = 66;
pub const IMAGINARY_NODE: u8 = 67;
pub const IMPLICIT_NODE: u8 = 68;
pub const IMPLICIT_REST_NODE: u8 = 69;
pub const INDEX_AND_WRITE_NODE: u8 = 70;
pub const INDEX_OPERATOR_WRITE_NODE: u8 = 71;
pub const INDEX_OR_WRITE_NODE: u8 = 72;
pub const INDEX_TARGET_NODE: u8 = 73;
pub const IN_NODE: u8 = 74;
pub const INSTANCE_VARIABLE_AND_WRITE_NODE: u8 = 75;
pub const INSTANCE_VARIABLE_OPERATOR_WRITE_NODE: u8 = 76;
pub const INSTANCE_VARIABLE_OR_WRITE_NODE: u8 = 77;
pub const INSTANCE_VARIABLE_READ_NODE: u8 = 78;
pub const INSTANCE_VARIABLE_TARGET_NODE: u8 = 79;
pub const INSTANCE_VARIABLE_WRITE_NODE: u8 = 80;
pub const INTEGER_NODE: u8 = 81;
pub const INTERPOLATED_MATCH_LAST_LINE_NODE: u8 = 82;
pub const INTERPOLATED_REGULAR_EXPRESSION_NODE: u8 = 83;
pub const INTERPOLATED_STRING_NODE: u8 = 84;
pub const INTERPOLATED_SYMBOL_NODE: u8 = 85;
pub const INTERPOLATED_X_STRING_NODE: u8 = 86;
pub const IT_LOCAL_VARIABLE_READ_NODE: u8 = 87;
pub const IT_PARAMETERS_NODE: u8 = 88;
pub const KEYWORD_HASH_NODE: u8 = 89;
pub const KEYWORD_REST_PARAMETER_NODE: u8 = 90;
pub const LAMBDA_NODE: u8 = 91;
pub const LOCAL_VARIABLE_AND_WRITE_NODE: u8 = 92;
pub const LOCAL_VARIABLE_OPERATOR_WRITE_NODE: u8 = 93;
pub const LOCAL_VARIABLE_OR_WRITE_NODE: u8 = 94;
pub const LOCAL_VARIABLE_READ_NODE: u8 = 95;
pub const LOCAL_VARIABLE_TARGET_NODE: u8 = 96;
pub const LOCAL_VARIABLE_WRITE_NODE: u8 = 97;
pub const MATCH_LAST_LINE_NODE: u8 = 98;
pub const MATCH_PREDICATE_NODE: u8 = 99;
pub const MATCH_REQUIRED_NODE: u8 = 100;
pub const MATCH_WRITE_NODE: u8 = 101;
pub const MISSING_NODE: u8 = 102;
pub const MODULE_NODE: u8 = 103;
pub const MULTI_TARGET_NODE: u8 = 104;
pub const MULTI_WRITE_NODE: u8 = 105;
pub const NEXT_NODE: u8 = 106;
pub const NIL_NODE: u8 = 107;
pub const NO_KEYWORDS_PARAMETER_NODE: u8 = 108;
pub const NUMBERED_PARAMETERS_NODE: u8 = 109;
pub const NUMBERED_REFERENCE_READ_NODE: u8 = 110;
pub const OPTIONAL_KEYWORD_PARAMETER_NODE: u8 = 111;
pub const OPTIONAL_PARAMETER_NODE: u8 = 112;
pub const OR_NODE: u8 = 113;
pub const PARAMETERS_NODE: u8 = 114;
pub const PARENTHESES_NODE: u8 = 115;
pub const PINNED_EXPRESSION_NODE: u8 = 116;
pub const PINNED_VARIABLE_NODE: u8 = 117;
pub const POST_EXECUTION_NODE: u8 = 118;
pub const PRE_EXECUTION_NODE: u8 = 119;
pub const PROGRAM_NODE: u8 = 120;
pub const RANGE_NODE: u8 = 121;
pub const RATIONAL_NODE: u8 = 122;
pub const REDO_NODE: u8 = 123;
pub const REGULAR_EXPRESSION_NODE: u8 = 124;
pub const REQUIRED_KEYWORD_PARAMETER_NODE: u8 = 125;
pub const REQUIRED_PARAMETER_NODE: u8 = 126;
pub const RESCUE_MODIFIER_NODE: u8 = 127;
pub const RESCUE_NODE: u8 = 128;
pub const REST_PARAMETER_NODE: u8 = 129;
pub const RETRY_NODE: u8 = 130;
pub const RETURN_NODE: u8 = 131;
pub const SELF_NODE: u8 = 132;
pub const SHAREABLE_CONSTANT_NODE: u8 = 133;
pub const SINGLETON_CLASS_NODE: u8 = 134;
pub const SOURCE_ENCODING_NODE: u8 = 135;
pub const SOURCE_FILE_NODE: u8 = 136;
pub const SOURCE_LINE_NODE: u8 = 137;
pub const SPLAT_NODE: u8 = 138;
pub const STATEMENTS_NODE: u8 = 139;
pub const STRING_NODE: u8 = 140;
pub const SUPER_NODE: u8 = 141;
pub const SYMBOL_NODE: u8 = 142;
pub const TRUE_NODE: u8 = 143;
pub const UNDEF_NODE: u8 = 144;
pub const UNLESS_NODE: u8 = 145;
pub const UNTIL_NODE: u8 = 146;
pub const WHEN_NODE: u8 = 147;
pub const WHILE_NODE: u8 = 148;
pub const X_STRING_NODE: u8 = 149;
pub const YIELD_NODE: u8 = 150;

/// Extract a u8 tag from a Node for dispatch table lookup.
/// The compiler optimizes this 151-arm match into a jump table.
#[inline]
pub fn node_type_tag(node: &ruby_prism::Node<'_>) -> u8 {
    match node {
        ruby_prism::Node::AliasGlobalVariableNode { .. } => 0,
        ruby_prism::Node::AliasMethodNode { .. } => 1,
        ruby_prism::Node::AlternationPatternNode { .. } => 2,
        ruby_prism::Node::AndNode { .. } => 3,
        ruby_prism::Node::ArgumentsNode { .. } => 4,
        ruby_prism::Node::ArrayNode { .. } => 5,
        ruby_prism::Node::ArrayPatternNode { .. } => 6,
        ruby_prism::Node::AssocNode { .. } => 7,
        ruby_prism::Node::AssocSplatNode { .. } => 8,
        ruby_prism::Node::BackReferenceReadNode { .. } => 9,
        ruby_prism::Node::BeginNode { .. } => 10,
        ruby_prism::Node::BlockArgumentNode { .. } => 11,
        ruby_prism::Node::BlockLocalVariableNode { .. } => 12,
        ruby_prism::Node::BlockNode { .. } => 13,
        ruby_prism::Node::BlockParameterNode { .. } => 14,
        ruby_prism::Node::BlockParametersNode { .. } => 15,
        ruby_prism::Node::BreakNode { .. } => 16,
        ruby_prism::Node::CallAndWriteNode { .. } => 17,
        ruby_prism::Node::CallNode { .. } => 18,
        ruby_prism::Node::CallOperatorWriteNode { .. } => 19,
        ruby_prism::Node::CallOrWriteNode { .. } => 20,
        ruby_prism::Node::CallTargetNode { .. } => 21,
        ruby_prism::Node::CapturePatternNode { .. } => 22,
        ruby_prism::Node::CaseMatchNode { .. } => 23,
        ruby_prism::Node::CaseNode { .. } => 24,
        ruby_prism::Node::ClassNode { .. } => 25,
        ruby_prism::Node::ClassVariableAndWriteNode { .. } => 26,
        ruby_prism::Node::ClassVariableOperatorWriteNode { .. } => 27,
        ruby_prism::Node::ClassVariableOrWriteNode { .. } => 28,
        ruby_prism::Node::ClassVariableReadNode { .. } => 29,
        ruby_prism::Node::ClassVariableTargetNode { .. } => 30,
        ruby_prism::Node::ClassVariableWriteNode { .. } => 31,
        ruby_prism::Node::ConstantAndWriteNode { .. } => 32,
        ruby_prism::Node::ConstantOperatorWriteNode { .. } => 33,
        ruby_prism::Node::ConstantOrWriteNode { .. } => 34,
        ruby_prism::Node::ConstantPathAndWriteNode { .. } => 35,
        ruby_prism::Node::ConstantPathNode { .. } => 36,
        ruby_prism::Node::ConstantPathOperatorWriteNode { .. } => 37,
        ruby_prism::Node::ConstantPathOrWriteNode { .. } => 38,
        ruby_prism::Node::ConstantPathTargetNode { .. } => 39,
        ruby_prism::Node::ConstantPathWriteNode { .. } => 40,
        ruby_prism::Node::ConstantReadNode { .. } => 41,
        ruby_prism::Node::ConstantTargetNode { .. } => 42,
        ruby_prism::Node::ConstantWriteNode { .. } => 43,
        ruby_prism::Node::DefinedNode { .. } => 44,
        ruby_prism::Node::DefNode { .. } => 45,
        ruby_prism::Node::ElseNode { .. } => 46,
        ruby_prism::Node::EmbeddedStatementsNode { .. } => 47,
        ruby_prism::Node::EmbeddedVariableNode { .. } => 48,
        ruby_prism::Node::EnsureNode { .. } => 49,
        ruby_prism::Node::FalseNode { .. } => 50,
        ruby_prism::Node::FindPatternNode { .. } => 51,
        ruby_prism::Node::FlipFlopNode { .. } => 52,
        ruby_prism::Node::FloatNode { .. } => 53,
        ruby_prism::Node::ForNode { .. } => 54,
        ruby_prism::Node::ForwardingArgumentsNode { .. } => 55,
        ruby_prism::Node::ForwardingParameterNode { .. } => 56,
        ruby_prism::Node::ForwardingSuperNode { .. } => 57,
        ruby_prism::Node::GlobalVariableAndWriteNode { .. } => 58,
        ruby_prism::Node::GlobalVariableOperatorWriteNode { .. } => 59,
        ruby_prism::Node::GlobalVariableOrWriteNode { .. } => 60,
        ruby_prism::Node::GlobalVariableReadNode { .. } => 61,
        ruby_prism::Node::GlobalVariableTargetNode { .. } => 62,
        ruby_prism::Node::GlobalVariableWriteNode { .. } => 63,
        ruby_prism::Node::HashNode { .. } => 64,
        ruby_prism::Node::HashPatternNode { .. } => 65,
        ruby_prism::Node::IfNode { .. } => 66,
        ruby_prism::Node::ImaginaryNode { .. } => 67,
        ruby_prism::Node::ImplicitNode { .. } => 68,
        ruby_prism::Node::ImplicitRestNode { .. } => 69,
        ruby_prism::Node::IndexAndWriteNode { .. } => 70,
        ruby_prism::Node::IndexOperatorWriteNode { .. } => 71,
        ruby_prism::Node::IndexOrWriteNode { .. } => 72,
        ruby_prism::Node::IndexTargetNode { .. } => 73,
        ruby_prism::Node::InNode { .. } => 74,
        ruby_prism::Node::InstanceVariableAndWriteNode { .. } => 75,
        ruby_prism::Node::InstanceVariableOperatorWriteNode { .. } => 76,
        ruby_prism::Node::InstanceVariableOrWriteNode { .. } => 77,
        ruby_prism::Node::InstanceVariableReadNode { .. } => 78,
        ruby_prism::Node::InstanceVariableTargetNode { .. } => 79,
        ruby_prism::Node::InstanceVariableWriteNode { .. } => 80,
        ruby_prism::Node::IntegerNode { .. } => 81,
        ruby_prism::Node::InterpolatedMatchLastLineNode { .. } => 82,
        ruby_prism::Node::InterpolatedRegularExpressionNode { .. } => 83,
        ruby_prism::Node::InterpolatedStringNode { .. } => 84,
        ruby_prism::Node::InterpolatedSymbolNode { .. } => 85,
        ruby_prism::Node::InterpolatedXStringNode { .. } => 86,
        ruby_prism::Node::ItLocalVariableReadNode { .. } => 87,
        ruby_prism::Node::ItParametersNode { .. } => 88,
        ruby_prism::Node::KeywordHashNode { .. } => 89,
        ruby_prism::Node::KeywordRestParameterNode { .. } => 90,
        ruby_prism::Node::LambdaNode { .. } => 91,
        ruby_prism::Node::LocalVariableAndWriteNode { .. } => 92,
        ruby_prism::Node::LocalVariableOperatorWriteNode { .. } => 93,
        ruby_prism::Node::LocalVariableOrWriteNode { .. } => 94,
        ruby_prism::Node::LocalVariableReadNode { .. } => 95,
        ruby_prism::Node::LocalVariableTargetNode { .. } => 96,
        ruby_prism::Node::LocalVariableWriteNode { .. } => 97,
        ruby_prism::Node::MatchLastLineNode { .. } => 98,
        ruby_prism::Node::MatchPredicateNode { .. } => 99,
        ruby_prism::Node::MatchRequiredNode { .. } => 100,
        ruby_prism::Node::MatchWriteNode { .. } => 101,
        ruby_prism::Node::MissingNode { .. } => 102,
        ruby_prism::Node::ModuleNode { .. } => 103,
        ruby_prism::Node::MultiTargetNode { .. } => 104,
        ruby_prism::Node::MultiWriteNode { .. } => 105,
        ruby_prism::Node::NextNode { .. } => 106,
        ruby_prism::Node::NilNode { .. } => 107,
        ruby_prism::Node::NoKeywordsParameterNode { .. } => 108,
        ruby_prism::Node::NumberedParametersNode { .. } => 109,
        ruby_prism::Node::NumberedReferenceReadNode { .. } => 110,
        ruby_prism::Node::OptionalKeywordParameterNode { .. } => 111,
        ruby_prism::Node::OptionalParameterNode { .. } => 112,
        ruby_prism::Node::OrNode { .. } => 113,
        ruby_prism::Node::ParametersNode { .. } => 114,
        ruby_prism::Node::ParenthesesNode { .. } => 115,
        ruby_prism::Node::PinnedExpressionNode { .. } => 116,
        ruby_prism::Node::PinnedVariableNode { .. } => 117,
        ruby_prism::Node::PostExecutionNode { .. } => 118,
        ruby_prism::Node::PreExecutionNode { .. } => 119,
        ruby_prism::Node::ProgramNode { .. } => 120,
        ruby_prism::Node::RangeNode { .. } => 121,
        ruby_prism::Node::RationalNode { .. } => 122,
        ruby_prism::Node::RedoNode { .. } => 123,
        ruby_prism::Node::RegularExpressionNode { .. } => 124,
        ruby_prism::Node::RequiredKeywordParameterNode { .. } => 125,
        ruby_prism::Node::RequiredParameterNode { .. } => 126,
        ruby_prism::Node::RescueModifierNode { .. } => 127,
        ruby_prism::Node::RescueNode { .. } => 128,
        ruby_prism::Node::RestParameterNode { .. } => 129,
        ruby_prism::Node::RetryNode { .. } => 130,
        ruby_prism::Node::ReturnNode { .. } => 131,
        ruby_prism::Node::SelfNode { .. } => 132,
        ruby_prism::Node::ShareableConstantNode { .. } => 133,
        ruby_prism::Node::SingletonClassNode { .. } => 134,
        ruby_prism::Node::SourceEncodingNode { .. } => 135,
        ruby_prism::Node::SourceFileNode { .. } => 136,
        ruby_prism::Node::SourceLineNode { .. } => 137,
        ruby_prism::Node::SplatNode { .. } => 138,
        ruby_prism::Node::StatementsNode { .. } => 139,
        ruby_prism::Node::StringNode { .. } => 140,
        ruby_prism::Node::SuperNode { .. } => 141,
        ruby_prism::Node::SymbolNode { .. } => 142,
        ruby_prism::Node::TrueNode { .. } => 143,
        ruby_prism::Node::UndefNode { .. } => 144,
        ruby_prism::Node::UnlessNode { .. } => 145,
        ruby_prism::Node::UntilNode { .. } => 146,
        ruby_prism::Node::WhenNode { .. } => 147,
        ruby_prism::Node::WhileNode { .. } => 148,
        ruby_prism::Node::XStringNode { .. } => 149,
        ruby_prism::Node::YieldNode { .. } => 150,
    }
}

/// Map an as_*_node method name to its node type tag.
/// Used by the auto-annotation validation test.
#[cfg(test)]
pub fn tag_from_method_name(name: &str) -> Option<u8> {
    match name {
        "as_alias_global_variable_node" => Some(0),
        "as_alias_method_node" => Some(1),
        "as_alternation_pattern_node" => Some(2),
        "as_and_node" => Some(3),
        "as_arguments_node" => Some(4),
        "as_array_node" => Some(5),
        "as_array_pattern_node" => Some(6),
        "as_assoc_node" => Some(7),
        "as_assoc_splat_node" => Some(8),
        "as_back_reference_read_node" => Some(9),
        "as_begin_node" => Some(10),
        "as_block_argument_node" => Some(11),
        "as_block_local_variable_node" => Some(12),
        "as_block_node" => Some(13),
        "as_block_parameter_node" => Some(14),
        "as_block_parameters_node" => Some(15),
        "as_break_node" => Some(16),
        "as_call_and_write_node" => Some(17),
        "as_call_node" => Some(18),
        "as_call_operator_write_node" => Some(19),
        "as_call_or_write_node" => Some(20),
        "as_call_target_node" => Some(21),
        "as_capture_pattern_node" => Some(22),
        "as_case_match_node" => Some(23),
        "as_case_node" => Some(24),
        "as_class_node" => Some(25),
        "as_class_variable_and_write_node" => Some(26),
        "as_class_variable_operator_write_node" => Some(27),
        "as_class_variable_or_write_node" => Some(28),
        "as_class_variable_read_node" => Some(29),
        "as_class_variable_target_node" => Some(30),
        "as_class_variable_write_node" => Some(31),
        "as_constant_and_write_node" => Some(32),
        "as_constant_operator_write_node" => Some(33),
        "as_constant_or_write_node" => Some(34),
        "as_constant_path_and_write_node" => Some(35),
        "as_constant_path_node" => Some(36),
        "as_constant_path_operator_write_node" => Some(37),
        "as_constant_path_or_write_node" => Some(38),
        "as_constant_path_target_node" => Some(39),
        "as_constant_path_write_node" => Some(40),
        "as_constant_read_node" => Some(41),
        "as_constant_target_node" => Some(42),
        "as_constant_write_node" => Some(43),
        "as_defined_node" => Some(44),
        "as_def_node" => Some(45),
        "as_else_node" => Some(46),
        "as_embedded_statements_node" => Some(47),
        "as_embedded_variable_node" => Some(48),
        "as_ensure_node" => Some(49),
        "as_false_node" => Some(50),
        "as_find_pattern_node" => Some(51),
        "as_flip_flop_node" => Some(52),
        "as_float_node" => Some(53),
        "as_for_node" => Some(54),
        "as_forwarding_arguments_node" => Some(55),
        "as_forwarding_parameter_node" => Some(56),
        "as_forwarding_super_node" => Some(57),
        "as_global_variable_and_write_node" => Some(58),
        "as_global_variable_operator_write_node" => Some(59),
        "as_global_variable_or_write_node" => Some(60),
        "as_global_variable_read_node" => Some(61),
        "as_global_variable_target_node" => Some(62),
        "as_global_variable_write_node" => Some(63),
        "as_hash_node" => Some(64),
        "as_hash_pattern_node" => Some(65),
        "as_if_node" => Some(66),
        "as_imaginary_node" => Some(67),
        "as_implicit_node" => Some(68),
        "as_implicit_rest_node" => Some(69),
        "as_index_and_write_node" => Some(70),
        "as_index_operator_write_node" => Some(71),
        "as_index_or_write_node" => Some(72),
        "as_index_target_node" => Some(73),
        "as_in_node" => Some(74),
        "as_instance_variable_and_write_node" => Some(75),
        "as_instance_variable_operator_write_node" => Some(76),
        "as_instance_variable_or_write_node" => Some(77),
        "as_instance_variable_read_node" => Some(78),
        "as_instance_variable_target_node" => Some(79),
        "as_instance_variable_write_node" => Some(80),
        "as_integer_node" => Some(81),
        "as_interpolated_match_last_line_node" => Some(82),
        "as_interpolated_regular_expression_node" => Some(83),
        "as_interpolated_string_node" => Some(84),
        "as_interpolated_symbol_node" => Some(85),
        "as_interpolated_x_string_node" => Some(86),
        "as_it_local_variable_read_node" => Some(87),
        "as_it_parameters_node" => Some(88),
        "as_keyword_hash_node" => Some(89),
        "as_keyword_rest_parameter_node" => Some(90),
        "as_lambda_node" => Some(91),
        "as_local_variable_and_write_node" => Some(92),
        "as_local_variable_operator_write_node" => Some(93),
        "as_local_variable_or_write_node" => Some(94),
        "as_local_variable_read_node" => Some(95),
        "as_local_variable_target_node" => Some(96),
        "as_local_variable_write_node" => Some(97),
        "as_match_last_line_node" => Some(98),
        "as_match_predicate_node" => Some(99),
        "as_match_required_node" => Some(100),
        "as_match_write_node" => Some(101),
        "as_missing_node" => Some(102),
        "as_module_node" => Some(103),
        "as_multi_target_node" => Some(104),
        "as_multi_write_node" => Some(105),
        "as_next_node" => Some(106),
        "as_nil_node" => Some(107),
        "as_no_keywords_parameter_node" => Some(108),
        "as_numbered_parameters_node" => Some(109),
        "as_numbered_reference_read_node" => Some(110),
        "as_optional_keyword_parameter_node" => Some(111),
        "as_optional_parameter_node" => Some(112),
        "as_or_node" => Some(113),
        "as_parameters_node" => Some(114),
        "as_parentheses_node" => Some(115),
        "as_pinned_expression_node" => Some(116),
        "as_pinned_variable_node" => Some(117),
        "as_post_execution_node" => Some(118),
        "as_pre_execution_node" => Some(119),
        "as_program_node" => Some(120),
        "as_range_node" => Some(121),
        "as_rational_node" => Some(122),
        "as_redo_node" => Some(123),
        "as_regular_expression_node" => Some(124),
        "as_required_keyword_parameter_node" => Some(125),
        "as_required_parameter_node" => Some(126),
        "as_rescue_modifier_node" => Some(127),
        "as_rescue_node" => Some(128),
        "as_rest_parameter_node" => Some(129),
        "as_retry_node" => Some(130),
        "as_return_node" => Some(131),
        "as_self_node" => Some(132),
        "as_shareable_constant_node" => Some(133),
        "as_singleton_class_node" => Some(134),
        "as_source_encoding_node" => Some(135),
        "as_source_file_node" => Some(136),
        "as_source_line_node" => Some(137),
        "as_splat_node" => Some(138),
        "as_statements_node" => Some(139),
        "as_string_node" => Some(140),
        "as_super_node" => Some(141),
        "as_symbol_node" => Some(142),
        "as_true_node" => Some(143),
        "as_undef_node" => Some(144),
        "as_unless_node" => Some(145),
        "as_until_node" => Some(146),
        "as_when_node" => Some(147),
        "as_while_node" => Some(148),
        "as_x_string_node" => Some(149),
        "as_yield_node" => Some(150),
        _ => None,
    }
}
